version: "3"

# More info at https://hub.docker.com/_/neo4j

name: neo4jdb

services:
  neo4j-service:
    container_name: neo4jdb-container
    image: neo4j:5-community
    # image: neo4j:community
    # image: neo4j:enterprise    #licensed.
    # environment:
    #   NEO4J_ACCEPT_LICENSE_AGREEMENT: eval    #Needed for enterprise.
    hostname: neo4j
    ports:
      - "127.0.0.1:7474:7474/tcp" #neo4j http
      - "127.0.0.1:7687:7687/tcp" #neo4j bolt
    #volumes:
      #- 'neo4jData:/data/'
      #- './neo4jData/:/data/'
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/var/lib/neo4j/bin/neo4j status"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 10s

  #Placeholder dependency to ensure DB is up and healthy
  hello-world-service:
    container_name: hello-neo4jdb-container
    image: hello-world
    depends_on:
      neo4j-service:
        condition: service_healthy

#volumes:
#  neo4jData:
