version: "3"

# More info at https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-develop-emulator

name: cosmosdb

services:
  cosmosdb-service:
    container_name: cosmosdb-container
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 5
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: true
      AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE: 127.0.0.1
      # AZURE_COSMOS_EMULATOR_ALLOW_NETWORK_ACESS: true
    hostname: cosmosdb
    ports:
      - "127.0.0.1:8081:8081/tcp"
      - "127.0.0.1:10250-10255:10250-10255/tcp"
    # volumes:
      #- 'cosmosData:/tmp/cosmos/appdata'
      # - './cosmosData/:/tmp/cosmos/appdata'
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f http://127.0.0.1:8081/_explorer/emulator.pem || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s

  #Placeholder dependency to ensure DB is up and healthy
  hello-world-service:
    container_name: hello-cosmosdb-container
    image: hello-world
    depends_on:
      cosmosdb-service:
        condition: service_healthy

#volumes:
#  cosmosdbData:
