--Create privileges (as sys on PDB)
CONN sys/example123#@localhost:1521/FREEPDB1 as SYSDBA
GRANT CREATE SESSION, SET CONTAINER TO dbv_owner IDENTIFIED BY dbv_owner123#;
GRANT CREATE SESSION, SET CONTAINER TO dbv_owner_backup IDENTIFIED BY dbv_owner_backup123#;
GRANT CREATE SESSION, SET CONTAINER TO dbv_acctmgr IDENTIFIED BY dbv_acctmgr123#;
GRANT CREATE SESSION, SET CONTAINER TO dbv_acctmgr_backup IDENTIFIED BY dbv_acctmgr_backup123#;

--Create user profile (as sys on PDB)
CONN sys/example123#@localhost:1521/FREEPDB1  as SYSDBA
CREATE PROFILE dv_profile limit
FAILED_LOGIN_ATTEMPTS UNLIMITED
PASSWORD_VERIFY_FUNCTION ORA12C_VERIFY_FUNCTION
PASSWORD_LOCK_TIME UNLIMITED
CONTAINER=CURRENT;

--Assign user profile (as sys on PDB)
CONN sys/example123#@localhost:1521/FREEPDB1  as SYSDBA
ALTER USER dbv_owner PROFILE dv_profile CONTAINER = CURRENT;
ALTER USER dbv_owner_backup PROFILE dv_profile CONTAINER = CURRENT;
ALTER USER dbv_acctmgr PROFILE dv_profile CONTAINER = CURRENT;
ALTER USER dbv_acctmgr_backup PROFILE dv_profile CONTAINER = CURRENT;

--Create audit policies (as sys on PDB)
CONN sys/example123#@localhost:1521/FREEPDB1  as SYSDBA
CREATE AUDIT POLICY dv_logins ACTIONS LOGON;
AUDIT POLICY dv_logins BY USERS WITH GRANTED ROLES DV_OWNER, DV_ACCTMGR WHENEVER NOT SUCCESSFUL;
